version: 2.1
      
commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name create-infrastructure
            
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: aws cloudformation deploy --stack-name create-infrastructure --template-file template.yml  --region=us-west-2
      - run: return 1
      - destroy_environment
        when: on_fail
        
workflows:
  my_workflow:
    jobs:
      - create_infrastructure
      - destroy_environment:
          requires:
            - create_infrastructure

