version: 2.1

commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name create-infrastructure --region=us-west-2

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Stack
          command: |
            aws cloudformation deploy --stack-name create-infrastructure --template-file template.yml  --region=us-west-2
      - run: return 1
          when: on_fail

workflows:
  my_workflow:
    jobs:
      - create_infrastructure
